from hpctools.utils import load_template, write_file, success, error

def generate_makefile(
    compiler: str = None,
    flags: str = None,
    ldflags: str = None,
    src: str = None,
    output: str = None,
    use_template: bool = False,
    template_name: str = "make_default.mk",
) -> bool:
    """
    Generate a Makefile either from a template or from direct parameters.

    Args:
        compiler (str): Compiler command.
        flags (str): Compilation flags.
        ldflags (str): Linker flags.
        src (str): Source files.
        output (str): Executable name.
        use_template (bool): Whether to load a template file.
        template_name (str): Template filename to use.

    Returns:
        bool: True if written successfully.
    """
    try:
        if use_template:
            # --- Load template and replace placeholders ---
            template = load_template(template_name)
            makefile = template.format(
                compiler=compiler or "gcc",
                flags=flags or "-O2 -Wall",
                ldflags=ldflags or "-lm",
                src=src or "main.c",
                output=output or "a.out",
            )
        else:
            # --- Fallback: generate directly from parameters ---
            makefile = f"""# Auto-generated by HPC Tools
CC = {compiler}
CFLAGS = {flags}
LDFLAGS = {ldflags}

SOURCE = {src}
OBJ = $(SOURCE:.c=.o)
TARGET = {output}

all: $(TARGET)

$(TARGET): $(OBJ)
\t$(CC) $(CFLAGS) $(OBJ) $(LDFLAGS) -o $@

%.o: %.c
\t$(CC) -c $(CFLAGS) $< -o $@

clean:
\t@echo "Cleaning project..."
\trm -f $(OBJ) $(TARGET)

.PHONY: all clean
"""

        write_file("Makefile", makefile)
        success("Makefile successfully generated.")
        return True

    except Exception as e:
        error(f"Failed to create Makefile: {e}")
        return False
